apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: demo
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 480429191117.dkr.ecr.us-east-1.amazonaws.com/frontend:f23179a
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: frontend-configmap
        imagePullPolicy: Always
      imagePullSecrets:
      - name: ecr-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: demo
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
  namespace: demo
data:
  REACT_APP_API_URL: "http://a84f55ccd10cb4efca5d8eea4cfbeddb-1103736086.us-east-1.elb.amazonaws.com"

