apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: demo
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 480429191117.dkr.ecr.us-east-1.amazonaws.com/backend:bae6164
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: backend-secrets
        imagePullPolicy: Always
      imagePullSecrets:
      - name: ecr-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: demo
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

