name: Frontend Build and Deploy 

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  ECR_REPO: frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: "arn:aws:iam::480429191117:role/FjahGitHubActionsECRPushRole"
        aws-region: ${{ env.AWS_REGION }}

    - name: Run unit test
      run: |
        cd frontend
        npm install
        npm test
      continue-on-error: true
      env:
        CI: false

    - name: Build Frontend APP upload static file to S3
      run: |
        cd frontend
        npm run build
        aws s3 cp build/ s3://frontend-app-1103736086 --recursive
      env:
        CI: false


